from pipelines.company_loader.contexts import CompanyDTO
from pipelines.generic_pipeline import Context, NextStep
from src.company.enums import SystemStatus


class CreateCompanyDTOStep:
    def __call__(self, context: Context, next_step: NextStep) -> None:
        dto = CompanyDTO(
            system_status=SystemStatus.AUTOGENERATED,
            country_code='RU',
            name=context.raw_company.name,
            legal_name=context.raw_company.legal_name,
            inn=context.raw_company.inn
        )
        context.company_dto = dto

        next_step(context)
