from pipelines.company_loader.context import CompanyDTO
from src.core.database.postgres.session_manager import DatabaseSessionManager
from pipelines.generic_pipeline import Context, NextStep, PipelineStep
from src.company.enums import SystemStatus
from src.company.scratch.sql_scratch import RawCompanyQueryManager


class CreateCompanyDTOStep(PipelineStep):
    _sessionmaker = None

    @classmethod
    def get_sessionmaker(cls):
        if cls._sessionmaker is None:
            cls._sessionmaker = DatabaseSessionManager.get_sessionmaker()
        return cls._sessionmaker


    def __call__(self, context: Context, next_step: NextStep) -> None:
        with self.get_sessionmaker()() as session:
            manager = RawCompanyQueryManager(session)
            if manager.get_by_inn(context.raw_company.inn):
                next_step.queue = []

            else:
                legal_description = None
                if context.raw_company.description_of_legal_entity:
                    legal_description = context.raw_company.description_of_legal_entity[2:-2].replace('\\', '').replace('"', '').replace('—', '')

                dto = CompanyDTO(
                    system_status=SystemStatus.AUTOGENERATED,
                    country_code="RU",
                    name=context.raw_company.name,
                    en_name=context.raw_company.en_name,
                    legal_name=context.raw_company.legal_name,
                    legal_address=context.raw_company.legal_address,
                    legal_description=legal_description,
                    inn=context.raw_company.inn,
                    ogrn=context.raw_company.ogrn,
                    kpp=context.raw_company.kpp,
                    okpo=context.raw_company.okpo,
                    okveds=context.raw_company.okved,
                    okogu_code=context.raw_company.okogu_code,
                    okopf_code=context.raw_company.okopf_code,
                    okfs_code=context.raw_company.okfs_code,
                    okato_code=context.raw_company.okato_code,
                    oktmo_code=context.raw_company.oktmo_code,
                    code_kladr=context.raw_company.code_kladr,
                )
                context.company_dto = dto

                next_step(context)
