version: '3.7'

services:
  marketplace:
    container_name: marketplace
    image: marketplace_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - marketplace_db

  marketplace_db:
    container_name: marketplace_db
    hostname: marketplace_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - marketplace_pg_data:/var/lib/postgresql/data
      - marketplace_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "15432:5432"

  marketplace_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: marketplace_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - "16379:6379"

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: russian-house