version: '3.7'

services:
  parser:
    container_name: parser
    image: app_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8100:8000"
    depends_on:
      - parser_db

  parser_db:
    container_name: parser_db
    hostname: parser_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "45432:5432"

  parser_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: parser_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - "46379:6379"

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"

networks:
  default:
    external: true
    name: russian-house