version: '3.7'
x-base_build: &x_base_build
  build:
    context: .
    dockerfile: ./Dockerfile

services:
#  app:
#    <<: [*x_base_build]
#    container_name: 21Yard
#    image: 21yard
#    env_file:
#      - .env
#    volumes:
#      - ./:/src
#      - /etc/ssl/21yard:/etc/ssl/certs
#    command: ["./scripts/start-dev.sh"]
#    ports:
#      - "8000:8000"
#    depends_on:
#      - app_db
#      - app_redis
#      - mongodb

  rh_db:
    container_name: rh_db
    hostname: rh_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/postgres:/scripts
    ports:
      - "15432:5432"

  rh_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: rh_redis
    env_file:
      - .env
    command:
      - 'redis-server'
#      - --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  rh_celery:
    <<: [*x_base_build]
    image: rh_celery
    container_name: rh_celery
    depends_on:
      - rh_redis
      - rh_celery_beat
    env_file:
      - .env
    command: ["./scripts/celery.sh", "celery"]

  rh_celery_beat:
    <<: [*x_base_build]
    image: rh_celery_beat
    container_name: rh_celery_beat
    depends_on:
      - rh_redis
    env_file:
      - .env
    command: [ "./scripts/celery.sh", "beat" ]

  rh_flower:
    <<: [*x_base_build]
    image: rh_flower
    container_name: rh_flower
    depends_on:
      - rh_redis
      - rh_celery
      - rh_celery_beat
    env_file:
      - .env
    command: [ "./scripts/celery.sh", "flower" ]
    ports:
      - "5555:5555"

volumes:
  pg_data:
    driver: "local"

networks:
  default:
    external: true
    name: rh
