version: '3.7'

services:
  marketplace:
    container_name: marketplace
    image: marketplace_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - marketplace_db

  marketplace_db:
    container_name: marketplace_db
    hostname: marketplace_db
    image: library/postgres:14.1
    env_file:
      - .env
    ports:
      - "25432:5432"

  marketplace_redis:
    image: redis:6.2-alpine
    hostname: redis
    container_name: marketplace_redis
    command:
      - 'redis-server'
      - '--requirepass myStrongPassword'
    ports:
      - "26379:6379"

networks:
  default:
    external: true
    name: russian-house
