import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional

from pipelines.company_loader.dto import (Contact, FinancialReport, Manager,
                                          TaxReport)
from pipelines.raw_model import RawCompany
from src.company.enums import LegalStatus, SystemStatus
from src.company.infrastructure.models import Company


@dataclass
class CompanyDTO:
    name: str
    en_name: str
    inn: str
    registration_date: Optional[datetime] = None
    liquidation_date: Optional[datetime] = None

    country_code: str = "RU"
    legal_status: LegalStatus = LegalStatus.UNKNOWN
    system_status: SystemStatus = SystemStatus.AUTOGENERATED

    legal_name: Optional[str] = None
    legal_address: Optional[str] = None
    ogrn: Optional[str] = None
    kpp: Optional[str] = None
    okpo: Optional[str] = None
    authorized_capital: Optional[int] = None
    average_number_of_employees: Optional[int] = None

    advantages: Optional[dict] = field(default_factory=list)

    okveds: Optional[dict] = None
    okved_ids: list[int] = field(default_factory=list)

    okogu_code: Optional[str] = None
    okopf_code: Optional[str] = None
    okfs_code: Optional[str] = None
    okato_code: Optional[str] = None
    oktmo_code: Optional[str] = None
    code_kladr: Optional[str] = None

    contacts: List[Contact] = field(default_factory=list)
    management: List[Manager] = field(default_factory=list)

    financial_reports: List[FinancialReport] = field(default_factory=list)
    tax_reports: List[TaxReport] = field(default_factory=list)


@dataclass
class CompanyContext:
    proxies: List[str]
    raw_company: RawCompany
    field_type_ids: Dict[str, uuid.UUID] = field(default_factory=dict)
    company_dto: Optional[CompanyDTO] = None
    company_model: Optional[Company] = None

    translated_advantages: Dict[str, str] = field(default_factory=dict)

    failed_records = 0
