"""init_tables

Revision ID: 72fff3c332bc
Revises: 
Create Date: 2024-10-27 23:18:19.976475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fff3c332bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('legal_form', sa.String(), nullable=False),
    sa.Column('legal_state', sa.String(), nullable=False),
    sa.Column('legal_address', sa.String(), nullable=False),
    sa.Column('legal_description', sa.String(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('kpp', sa.String(), nullable=False),
    sa.Column('okpo', sa.String(), nullable=False),
    sa.Column('registration_date', sa.String(), nullable=False),
    sa.Column('authorized_capital', sa.String(), nullable=False),
    sa.Column('director_fio', sa.String(), nullable=False),
    sa.Column('director_since', sa.String(), nullable=False),
    sa.Column('quantity_employees', sa.String(), nullable=False),
    sa.Column('sanctions', sa.String(), nullable=False),
    sa.Column('advantages', sa.String(), nullable=False),
    sa.Column('okogu', sa.String(), nullable=False),
    sa.Column('okopf', sa.String(), nullable=False),
    sa.Column('okfs', sa.String(), nullable=False),
    sa.Column('okato', sa.String(), nullable=False),
    sa.Column('oktmo', sa.String(), nullable=False),
    sa.Column('kladr', sa.String(), nullable=False),
    sa.Column('faxes_profile', sa.String(), nullable=False),
    sa.Column('financial_profile', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_pkey')),
    sa.UniqueConstraint('inn', name=op.f('company_inn_key')),
    sa.UniqueConstraint('legal_name', name=op.f('company_legal_name_key')),
    sa.UniqueConstraint('name', name=op.f('company_name_key')),
    sa.UniqueConstraint('ogrn', name=op.f('company_ogrn_key'))
    )
    op.create_table('company_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('company_contacts_pkey'))
    )
    op.create_table('okved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['okved.id'], name=op.f('okved_parent_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('okved_pkey'))
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_role_pkey'))
    )
    op.create_table('company_okved_m2m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('okved_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('company_okved_m2m_company_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['okved_id'], ['okved.id'], name=op.f('company_okved_m2m_okved_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_okved_m2m_pkey'))
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.String(length=60), nullable=True),
    sa.Column('telegram_id', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('middle_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_email_confirm', sa.Boolean(), nullable=False),
    sa.Column('is_phone_number_confirm', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], name=op.f('user_role_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key')),
    sa.UniqueConstraint('telegram_id', name=op.f('user_telegram_id_key')),
    sa.UniqueConstraint('telegram_username', name=op.f('user_telegram_username_key'))
    )
    op.create_table('company_user_m2m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('company_user_m2m_company_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('company_user_m2m_user_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('company_user_m2m_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_user_m2m')
    op.drop_table('user')
    op.drop_table('company_okved_m2m')
    op.drop_table('user_role')
    op.drop_table('okved')
    op.drop_table('company_contacts')
    op.drop_table('company')
    # ### end Alembic commands ###
