"""mktu_table

Revision ID: 185533c38c12
Revises: 05a599506a44
Create Date: 2025-03-15 12:55:59.146467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185533c38c12'
down_revision = '05a599506a44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MKTU_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('classifier_id', sa.Integer(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classifier_id'], ['MKTU_classifier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    op.drop_column('MKTU_classifier', 'products_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MKTU_classifier', sa.Column('products_en', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('classifier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['classifier_id'], ['MKTU_classifier.id'], name='products_classifier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.drop_table('MKTU_categories')
    # ### end Alembic commands ###
