"""company_m2m_okved

Revision ID: 913608bb34b8
Revises: 185533c38c12
Create Date: 2025-03-15 22:36:03.500081

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '913608bb34b8'
down_revision = '185533c38c12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_m2m_okved',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('okved_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['okved_id'], ['okved_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Enum('DIRECTOR', 'CEO', 'FOUNDER', 'SALES_MANAGER', 'PURCHASE_MANAGER', 'LOGIST', 'ACCOUNTANT', 'MANAGER', name='manager_type'), nullable=False),
    sa.Column('inn', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('en_full_name', sa.Text(), nullable=True),
    sa.Column('since_on_position', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('translations')
    op.add_column('custom_fields', sa.Column('translation_type', sa.Enum('AUTO', 'USER', name='translation_type'), nullable=True))
    op.alter_column('custom_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('legal_fields', sa.Column('translation_type', sa.Enum('AUTO', 'USER', name='translation_type'), nullable=True))
    op.alter_column('legal_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('system_fields', sa.Column('translation_type', sa.Enum('AUTO', 'USER', name='translation_type'), nullable=True))
    op.alter_column('system_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('system_fields', 'translation_type')
    op.alter_column('legal_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('legal_fields', 'translation_type')
    op.alter_column('custom_fields', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('custom_fields', 'translation_type')
    op.create_table('translations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', postgresql.ENUM('COMPANY', 'LEGAL_FIELD', 'SYSTEM_FIELD', 'CUSTOM_FIELD', 'CONTACT', 'FINANCIAL_REPORT', 'TAX_REPORT', 'TRANSLATION', name='entitytype'), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='translations_pkey'),
    sa.UniqueConstraint('entity_id', 'entity_type', 'field_name', 'language_code', name='uq_translation')
    )
    op.drop_table('managers')
    op.drop_table('company_m2m_okved')
    # ### end Alembic commands ###
