"""add_new_indx

Revision ID: 5c21c99f6e10
Revises: a224ea6cf30e
Create Date: 2025-03-27 23:27:46.449240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c21c99f6e10'
down_revision = 'a224ea6cf30e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_company_id', 'companies', ['id'], unique=False)
    op.create_index('idx_companyfieldtype_id', 'company_field_type', ['id'], unique=False)
    op.create_index('idx_companyfield_company_id', 'company_fields', ['company_id'], unique=False)
    op.create_index('idx_companyfield_type_id', 'company_fields', ['company_field_type_id'], unique=False)
    op.create_index('idx_fieldtranslation_composite', 'field_translations', ['field_id', 'language_code', 'data'], unique=False)
    op.create_index('idx_fieldtypetranslation_composite', 'field_type_translations', ['field_type_id', 'language_code', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fieldtypetranslation_composite', table_name='field_type_translations')
    op.drop_index('idx_fieldtranslation_composite', table_name='field_translations')
    op.drop_index('idx_companyfield_type_id', table_name='company_fields')
    op.drop_index('idx_companyfield_company_id', table_name='company_fields')
    op.drop_index('idx_companyfieldtype_id', table_name='company_field_type')
    op.drop_index('idx_company_id', table_name='companies')
    # ### end Alembic commands ###
