"""refactoring_company

Revision ID: 62fa1eac2d03
Revises: 2800e0e5fc6d
Create Date: 2025-03-26 20:56:00.470653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fa1eac2d03'
down_revision = '2800e0e5fc6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_translations', sa.Column('name', sa.Text(), nullable=False))
    op.drop_column('company_translations', 'advantages')
    op.drop_column('company_translations', 'legal_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_translations', sa.Column('legal_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('company_translations', sa.Column('advantages', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('company_translations', 'name')
    # ### end Alembic commands ###
