"""refactoring_company

Revision ID: ec8f40aa56d2
Revises: dbbac372b284
Create Date: 2025-03-26 22:38:54.876054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8f40aa56d2'
down_revision = 'dbbac372b284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
