"""okveds

Revision ID: c086278da415
Revises: eb01851e5507
Create Date: 2025-03-09 23:01:40.311246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c086278da415'
down_revision = 'eb01851e5507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('okved_nodes', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('okved_nodes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('okved_nodes', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('okved_nodes', 'name')
    # ### end Alembic commands ###
