"""okveds

Revision ID: 05a599506a44
Revises: c086278da415
Create Date: 2025-03-15 11:54:52.389808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a599506a44'
down_revision = 'c086278da415'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MKTU_classifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('include', sa.Text(), nullable=True),
    sa.Column('exclude', sa.Text(), nullable=True),
    sa.Column('type_en', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('include_en', sa.Text(), nullable=True),
    sa.Column('exclude_en', sa.Text(), nullable=True),
    sa.Column('products_en', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('classifier_id', sa.Integer(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classifier_id'], ['MKTU_classifier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('okved_nodes', sa.Column('en_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('okved_nodes', 'en_name')
    op.drop_table('products')
    op.drop_table('MKTU_classifier')
    # ### end Alembic commands ###
