"""refactoring_company

Revision ID: dbbac372b284
Revises: 62fa1eac2d03
Create Date: 2025-03-26 21:46:24.812403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbac372b284'
down_revision = '62fa1eac2d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_fields', sa.Column('code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_fields', 'code')
    # ### end Alembic commands ###
