"""add_company_indx

Revision ID: a224ea6cf30e
Revises: ec8f40aa56d2
Create Date: 2025-03-27 22:35:11.152312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a224ea6cf30e'
down_revision = 'ec8f40aa56d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_code_not_null', 'company_fields', ['code'], unique=False, postgresql_where=sa.text('code IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_code_not_null', table_name='company_fields', postgresql_where=sa.text('code IS NOT NULL'))
    # ### end Alembic commands ###
