from enum import Enum


class TranslationType(str, Enum):
    AUTO = 'AUTO'
    USER = 'USER'


class LegalStatus(str, Enum):
    ACTIVE = 'ACTIVE'
    LIQUIDATED = 'LIQUIDATED'
    BANKRUPTCY = 'BANKRUPTCY'
    EXCLUDED_FROM_REGISTER = 'EXCLUDED_FROM_REGISTER'
    SUSPENDED = 'SUSPENDED'
    UNKNOWN = 'UNKNOWN'
    ON_MODERATION = 'ON_MODERATION'


class SystemStatus(str, Enum):
    OWNER_CONTROLLED = 'OWNER_CONTROLLED'
    AUTOGENERATED = 'AUTOGENERATED'


class ReportStatus(str, Enum):
    DRAFT = 'DRAFT'
    SUBMITTED = 'SUBMITTED'
    VERIFIED = 'VERIFIED'
    REJECTED = 'REJECTED'


class ContactType(str, Enum):
    EMAIL = 'EMAIL'
    PHONE = 'PHONE'
    WEBSITE = 'WEBSITE'
    SOCIAL = 'SOCIAL'


class EntityType(str, Enum):
    COMPANY = 'COMPANY'
    LEGAL_FIELD = 'LEGAL_FIELD'
    SYSTEM_FIELD = 'SYSTEM_FIELD'
    CUSTOM_FIELD = 'CUSTOM_FIELD'
    CONTACT = 'CONTACT'
    FINANCIAL_REPORT = 'FINANCIAL_REPORT'
    TAX_REPORT = 'TAX_REPORT'
    TRANSLATION = 'TRANSLATION'


class FieldType(str, Enum):
    STRING = 'STRING'
    NUMBER = 'NUMBER'
    DATE = 'DATE'
    BOOLEAN = 'BOOLEAN'
    ARRAY = 'ARRAY'
    OBJECT = 'OBJECT'


class FiledStatus(str, Enum):
    DRAFT = 'DRAFT'
    ACTIVATE = 'ACTIVE'
    ARCHIVED = 'ARCHIVE'


class ValidationType(str, Enum):
    REGEX = 'REGEX'
    LENGTH = 'LENGTH'
    RANGE = 'RANGE'
    CUSTOM = 'CUSTOM'


class ManagerType(str, Enum):
    DIRECTOR = 'DIRECTOR'
    CEO = 'CEO'
    FOUNDER = 'FOUNDER'
    SALES_MANAGER= 'SALES MANAGER'
    PURCHASE_MANAGER = 'PURCHASE MANAGER'
    LOGIST = 'LOGIST'
    ACCOUNTANT = 'ACCOUNTANT'
    MANAGER = 'MANAGER'


class AddressType:
    LEGAL_ADDRESS = 'LEGAL_ADDRESS'
    OFFICE_ADDRESS = 'OFFICE_ADDRESS'
