from sqlalchemy import (Column, String, Integer, Boolean, ForeignKey, DateTime, DECIMAL, Text, Enum, func,
                        UniqueConstraint, Index)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from uuid import uuid4

from src import Base
from src.company.enums import LegalStatus, EntityType, FieldType, ValidationType, ContactType, \
    ReportStatus, SystemStatus, TranslationType, ManagerType, DataType


class Company(Base):
    __tablename__ = 'companies'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    country_code = Column(String(2), nullable=False)
    legal_status = Column(
        Enum(LegalStatus, name='legal_status'),
        nullable=False,
        default=LegalStatus.UNKNOWN
    )
    system_status = Column(
        Enum(SystemStatus, name='system_status'),
        nullable=False,
        default=SystemStatus.AUTOGENERATED
    )
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now())
    updated_at = Column(DateTime(timezone=True), nullable=False, default=func.now())

    fields = relationship("CompanyField", back_populates="company", cascade="all, delete-orphan")

    contacts = relationship("Contact", back_populates="company", cascade="all, delete-orphan")
    managers = relationship("Manager", back_populates="company", cascade="all, delete-orphan")

    financial_reports = relationship("FinancialReport", back_populates="company", cascade="all, delete-orphan")
    tax_reports = relationship("TaxReport", back_populates="company", cascade="all, delete-orphan")

    change_logs = relationship("CompanyChangeLog", back_populates="company", cascade="all, delete-orphan")

    __table_args__ = (
        Index('idx_company_country_code', country_code),
        Index('idx_legal_status', legal_status),
    )

    def add_legal_field(
            self,
            company_id,
            requirement_id,
            ru_data,
            en_data,
            json_data,
    ):
        legal_field = CompanyField(
            company_id=company_id,
            requirement_id=requirement_id,
            ru_data=ru_data,
            en_data=en_data,
            json_data=json_data,
        )
        self.legal_fields.append(legal_field)
        return legal_field

    def add_contact(self, contact_type, value):
        contact = Contact(
            company_id=self.id,
            type=contact_type,
            value=value
        )
        self.contacts.append(contact)
        return contact

    def add_financial_report(self, year, annual_income, net_profit, currency):
        report = FinancialReport(
            company_id=self.id,
            year=year,
            annual_income=annual_income,
            net_profit=net_profit,
            currency=currency,
            status=ReportStatus.DRAFT
        )
        self.financial_reports.append(report)
        return report

    def add_tax_report(self, year, quarter, period_start, period_end):
        report = TaxReport(
            company_id=self.id,
            year=year,
            quarter=quarter,
            period_start=period_start,
            period_end=period_end,
            status=ReportStatus.DRAFT
        )
        self.tax_reports.append(report)
        return report


class CompanyField(Base):
    __tablename__ = 'company_fields'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    requirement_id = Column(UUID(as_uuid=True), ForeignKey('requirement_fields.id'), nullable=False)

    ru_data = Column(Text, nullable=True)
    en_data = Column(Text, nullable=True)

    json_data = Column(JSONB, nullable=True)

    translation_config = Column(JSONB, nullable=True)

    company = relationship("Company", back_populates="company_fields")


class CompanyOKVED(Base):
    __tablename__ = 'company_m2m_okved'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    okved_id = Column(Integer, ForeignKey('okved_nodes.id'), nullable=False)


class CompanyFieldType(Base):
    __tablename__ = 'company_field_type'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)

    ru_name = Column(String(50), nullable=False)
    en_name = Column(String(50), nullable=False)

    ru_description = Column(Text, nullable=True)
    en_description = Column(Text, nullable=True)

    data_type = Column(Enum(DataType, name='data_type'), nullable=False)
    field_type = Column(Enum(FieldType, name='field_type'), nullable=False)
    display_order = Column(Integer, nullable=False)
    required = Column(Boolean, nullable=False, default=False)

    validation_rules = relationship("ValidationRule", back_populates="field", cascade="all, delete-orphan")

    __table_args__ = (
        UniqueConstraint('ru_name', name='uq_company_field_type'),
    )


class ValidationRule(Base):
    __tablename__ = 'validation_rules'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    field_id = Column(UUID(as_uuid=True), ForeignKey('required_fields.id'), nullable=False)
    validation_type = Column(Enum(ValidationType, name='validation_type'), nullable=False)
    params = Column(JSONB, nullable=False)
    error_code = Column(String(50), nullable=False)

    field = relationship("CountryField", back_populates="validation_rules")


class Manager(Base):
    __tablename__ = 'managers'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)

    position = Column(Enum(ManagerType, name='manager_type'), nullable=False)
    inn = Column(Text, nullable=True)

    full_name = Column(Text, nullable=True)
    en_full_name = Column(Text, nullable=True)

    since_on_position = Column(DateTime(timezone=True), nullable=True)

    company = relationship("Company", back_populates="managers")


class Contact(Base):
    __tablename__ = 'contacts'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    type = Column(Enum(ContactType, name='contact_type'), nullable=False)
    value = Column(Text, nullable=False)

    is_verified = Column(Boolean, nullable=False, default=False)

    company = relationship("Company", back_populates="contacts")


class FinancialReport(Base):
    __tablename__ = 'financial_reports'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    year = Column(Integer, nullable=False)
    annual_income = Column(DECIMAL(20, 2), nullable=False)
    net_profit = Column(DECIMAL(20, 2), nullable=False)
    currency = Column(String(3), nullable=False)
    status = Column(Enum(ReportStatus, name='report_status'), nullable=False)
    audited_by = Column(Integer, ForeignKey('users.id'))

    company = relationship("Company", back_populates="financial_reports")


class TaxReport(Base):
    __tablename__ = 'tax_reports'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    year = Column(Integer, nullable=False)
    quarter = Column(Integer, nullable=False)
    period_start = Column(DateTime(timezone=True), nullable=False)
    period_end = Column(DateTime(timezone=True), nullable=False)
    status = Column(Enum(ReportStatus, name='report_status'), nullable=False)

    company = relationship("Company", back_populates="tax_reports")


class CompanyChangeLog(Base):
    __tablename__ = 'company_change_log'
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    company_id = Column(UUID(as_uuid=True), ForeignKey('companies.id'), nullable=False)
    entity_type = Column(Enum(EntityType, name='entity_type'), nullable=False)
    entity_id = Column(UUID(as_uuid=True), nullable=False)
    timestamp = Column(DateTime(timezone=True), nullable=False, default=func.now())
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    reason = Column(Text)
    changes = Column(JSONB, nullable=False)

    company = relationship("Company", back_populates="change_logs")
