from enum import Enum


class UserRoleEnum(str, Enum):
    ADMIN = "ADMIN"
    DEFAULT = "DEFAULT"

class ActiveState(Enum):
    ACTIVE = "ACTIVE"
    BAN = "BAN"
    INACTIVE = "INACTIVE"
    WAIT_FOR_VERIFICATION = "WAIT_FOR_VERIFICATION"


class CreationMethod(Enum):
    AUTOGENERATED = "AUTOGENERATED"
    REGISTERED = "REGISTERED"


class AuthProvider(Enum):
    EMAIL = "EMAIL"
    GOOGLE = "GOOGLE"
    YANDEX = "YANDEX"
    VK = "VK"
